- job:
    name: itests-configure-vm
    node: integration-vm
    project-type: freestyle
    description: "<b>Title</b>: Part of the integration gating process.<br/>\
                \n<b>Description</b>: This job installs tox, configures savanna, configures pip parameters for integration tests.<br/>\
                \n<b>Maintainer</b>: Vadim Rovachev<br/>"
    defaults: global
    disabled: true
    concurrent: false

    scm:
     - git:
        url: https://github.com/stackforge/savanna.git
        refspec: $GERRIT_REFSPEC
        name:
        strategy: gerrit
        skip-tag: false
        wipe-workspace: false
        branches:
         - "$GERRIT_BRANCH"

    builders:
    - shell: "\
              #!/bin/bash\
              \n
              \nBUILD_ID=dontKill\
              \n
              \nsudo pip install tox\
              \nmkdir /tmp/cache\
              \n
              \nexport ADDR=`ifconfig eth0| awk -F ' *|:' '/inet addr/{print $4}'`\
              \n
              \necho \"[DEFAULT]\
              \nos_auth_host=172.18.79.139\
              \nos_admin_username=admin\
              \nos_admin_password=swordfish\
              \nos_admin_tenant_name=admin\
              \nplugins=vanilla\
              \n[cluster_node]\
              \n[sqlalchemy]\
              \n[plugin:vanilla]\
              \nplugin_class=savanna.plugins.vanilla.plugin:VanillaProvider\" >> etc/savanna/savanna.conf\
              \n
              \necho \"\
              \n[global]\
              \ntimeout = 60\
              \nindex-url = http://savanna-ci.vm.mirantis.net/pypi/savanna/\
              \nextra-index-url = https://pypi.python.org/simple/\
              \ndownload-cache = /tmp/cache\
              \n[install]\
              \nuse-mirrors = true\
              \nfind-links = http://savanna-ci.vm.mirantis.net:8181/simple/\
              \n\" > ~/.pip/pip.conf\
              \nscreen -dmS savanna-api tox -evenv -- savanna-api --config-file etc/savanna/savanna.conf -d --log-file log.txt"

    publishers:
      - email:
          recipients: vrovachev@mirantis.com
